In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("dataset/archive/CVD_cleaned.csv")

In [3]:
df.head(5)

General_Health                  Checkup Exercise Heart_Disease Skin_Cancer  \
0           Poor  Within the past 2 years       No            No          No   
1      Very Good     Within the past year       No           Yes          No   
2      Very Good     Within the past year      Yes            No          No   
3           Poor     Within the past year      Yes           Yes          No   
4           Good     Within the past year       No            No          No   

  Other_Cancer Depression Diabetes Arthritis     Sex Age_Category  \
0           No         No       No       Yes  Female        70-74   
1           No         No      Yes        No  Female        70-74   
2           No         No      Yes        No  Female        60-64   
3           No         No      Yes        No    Male        75-79   
4           No         No       No        No    Male          80+   

   Height_(cm)  Weight_(kg)    BMI Smoking_History  Alcohol_Consumption  \
0        150.0        32.66  14.54             Yes                  0.0   
1        165.0        77.11  28.29              No                  0.0   
2        163.0        88.45  33.47              No                  4.0   
3        180.0        93.44  28.73              No                  0.0   
4        191.0        88.45  24.37             Yes                  0.0   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  
0               30.0                          16.0                     12.0  
1               30.0                           0.0                      4.0  
2               12.0                           3.0                     16.0  
3               30.0                          30.0                      8.0  
4                8.0                           4.0                      0.0

In [4]:
df.isnull().sum() > 0

General_Health                  False
Checkup                         False
Exercise                        False
Heart_Disease                   False
Skin_Cancer                     False
Other_Cancer                    False
Depression                      False
Diabetes                        False
Arthritis                       False
Sex                             False
Age_Category                    False
Height_(cm)                     False
Weight_(kg)                     False
BMI                             False
Smoking_History                 False
Alcohol_Consumption             False
Fruit_Consumption               False
Green_Vegetables_Consumption    False
FriedPotato_Consumption         False
dtype: bool

In [5]:
##transformar em numérico

In [6]:
df['General_Health'].unique()

array(['Poor', 'Very Good', 'Good', 'Fair', 'Excellent'], dtype=object)

'Poor', 'Very Good', 'Good', 'Fair', 'Excellent' == variable ordinal 

In [7]:
General_Healthmap = {'Poor' : 0 , 'Very Good': 3, 'Good': 2, 'Fair' : 1, 'Excellent' : 4}

df['General_Health'] =  df['General_Health'].map(General_Healthmap)
df['General_Health'].unique()

array([0, 3, 2, 1, 4], dtype=int64)

In [8]:
yesmap = {'Yes' : 1, 'No' : 0}
yesmap

{'Yes': 1, 'No': 0}

In [9]:
df['Exercise'] = df['Exercise'].map(yesmap)
df['Exercise']

0         0
1         0
2         1
3         1
4         0
         ..
308849    1
308850    1
308851    1
308852    1
308853    1
Name: Exercise, Length: 308854, dtype: int64

In [10]:
df['Heart_Disease'] = df['Heart_Disease'].map(yesmap)
df['Heart_Disease']

0         0
1         1
2         0
3         1
4         0
         ..
308849    0
308850    0
308851    0
308852    0
308853    0
Name: Heart_Disease, Length: 308854, dtype: int64

In [11]:
df['Depression'] = df['Depression'].map(yesmap)
df['Depression']

0         0
1         0
2         0
3         0
4         0
         ..
308849    0
308850    0
308851    1
308852    0
308853    0
Name: Depression, Length: 308854, dtype: int64

In [12]:
df['Alcohol_Consumption']

0         0.0
1         0.0
2         4.0
3         0.0
4         0.0
         ... 
308849    4.0
308850    8.0
308851    4.0
308852    3.0
308853    1.0
Name: Alcohol_Consumption, Length: 308854, dtype: float64

In [13]:
df['Skin_Cancer'] = df['Skin_Cancer'].map(yesmap)
df['Skin_Cancer']

0         0
1         0
2         0
3         0
4         0
         ..
308849    0
308850    0
308851    0
308852    0
308853    0
Name: Skin_Cancer, Length: 308854, dtype: int64

In [14]:
df['Other_Cancer'] = df['Other_Cancer'].map(yesmap)
df['Other_Cancer']

0         0
1         0
2         0
3         0
4         0
         ..
308849    0
308850    0
308851    0
308852    0
308853    0
Name: Other_Cancer, Length: 308854, dtype: int64

In [15]:
df['Arthritis']=df['Arthritis'].map(yesmap)
df['Arthritis']

0         1
1         0
2         0
3         0
4         0
         ..
308849    0
308850    0
308851    0
308852    0
308853    0
Name: Arthritis, Length: 308854, dtype: int64

In [16]:
##sex is binary male = 1
sexmap = {'Male' : 1, 'Female' : 0}

In [17]:
df['IsMale'] = df['Sex'].map(sexmap)
df['IsMale']
df.drop(columns='Sex', inplace = True)

In [18]:
df['Smoking_History'] = df['Smoking_History'].map(yesmap)
df['Smoking_History']

0         1
1         0
2         0
3         0
4         1
         ..
308849    0
308850    0
308851    1
308852    0
308853    0
Name: Smoking_History, Length: 308854, dtype: int64

In [19]:
df['Checkup'].unique()

array(['Within the past 2 years', 'Within the past year',
       '5 or more years ago', 'Within the past 5 years', 'Never'],
      dtype=object)

# CheckUp - ordinal
'Within the past 2 years', 'Within the past year', '5 or more years ago', 'Within the past 5 years', 'Never'] -ordinal

In [20]:
CheckUpmap = {'Within the past year' : 0 , 'Within the past 2 years' : 1,  'Within the past 5 years' : 2 , '5 or more years ago' : 3, 
                'Never' : 4}
CheckUpmap

{'Within the past year': 0,
 'Within the past 2 years': 1,
 'Within the past 5 years': 2,
 '5 or more years ago': 3,
 'Never': 4}

In [21]:
df['Checkup'] = df['Checkup'].map(CheckUpmap)
df['Checkup'].unique()


array([1, 0, 3, 2, 4], dtype=int64)

In [22]:
diabetes = pd.get_dummies(data = df['Diabetes'], prefix = "Diabetes_")
diabetes.head()

df = pd.concat([df, diabetes], axis=1)
df.head()


General_Health  Checkup  Exercise  Heart_Disease  Skin_Cancer  \
0               0        1         0              0            0   
1               3        0         0              1            0   
2               3        0         1              0            0   
3               0        0         1              1            0   
4               2        0         0              0            0   

   Other_Cancer  Depression Diabetes  Arthritis Age_Category  ...  \
0             0           0       No          1        70-74  ...   
1             0           0      Yes          0        70-74  ...   
2             0           0      Yes          0        60-64  ...   
3             0           0      Yes          0        75-79  ...   
4             0           0       No          0          80+  ...   

   Smoking_History  Alcohol_Consumption  Fruit_Consumption  \
0                1                  0.0               30.0   
1                0                  0.0               30.0   
2                0                  4.0               12.0   
3                0                  0.0               30.0   
4                1                  0.0                8.0   

   Green_Vegetables_Consumption  FriedPotato_Consumption  IsMale  \
0                          16.0                     12.0       0   
1                           0.0                      4.0       0   
2                           3.0                     16.0       0   
3                          30.0                      8.0       1   
4                           4.0                      0.0       1   

   Diabetes__No  Diabetes__No, pre-diabetes or borderline diabetes  \
0             1                                                  0   
1             0                                                  0   
2             0                                                  0   
3             0                                                  0   
4             1                                                  0   

   Diabetes__Yes  Diabetes__Yes, but female told only during pregnancy  
0              0                                                  0     
1              1                                                  0     
2              1                                                  0     
3              1                                                  0     
4              0                                                  0     

[5 rows x 23 columns]

In [23]:
df.drop(columns='Diabetes' , inplace=True)

In [24]:
df['Age_Category'].unique()

array(['70-74', '60-64', '75-79', '80+', '65-69', '50-54', '45-49',
       '18-24', '30-34', '55-59', '35-39', '40-44', '25-29'], dtype=object)

In [25]:

Agecatmap = {'18-24' : 1 ,  '25-29' : 2, '30-34' : 3,  '35-39' : 4, '40-44' : 5 , '45-49' : 6,'50-54' : 7, '55-59' : 8 ,'60-64' : 9,  '65-69' : 10 ,'70-74' : 11 ,'75-79' : 12, '80+' : 13}

In [26]:
df['Age_Category'] = df['Age_Category'].map(Agecatmap)
df['Age_Category'].unique()

array([11,  9, 12, 13, 10,  7,  6,  1,  3,  8,  4,  5,  2], dtype=int64)

In [27]:
df.dtypes

General_Health                                            int64
Checkup                                                   int64
Exercise                                                  int64
Heart_Disease                                             int64
Skin_Cancer                                               int64
Other_Cancer                                              int64
Depression                                                int64
Arthritis                                                 int64
Age_Category                                              int64
Height_(cm)                                             float64
Weight_(kg)                                             float64
BMI                                                     float64
Smoking_History                                           int64
Alcohol_Consumption                                     float64
Fruit_Consumption                                       float64
Green_Vegetables_Consumption            